packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalog:
  '@antfu/ni': ^24.3.0
  '@antfu/nip': ^0.1.0
  '@antfu/utils': ^9.2.0
  '@vitejs/plugin-vue': ^5.2.0
  '@xiaohe01/eslint-config': ^1.5.1
  '@xiaohe01/tsconfig': ^1.0.4
  bumpp: ^10.1.0
  eslint: ^9.26.0
  esno: ^4.8.0
  html2canvas-pro: ^1.5.8
  husky: ^9.1.7
  lint-staged: ^15.5.2
  sass-embedded: ^1.85.0
  simple-git-hooks: ^2.13.0
  typescript: ~5.6.3
  ui-utils-kit: ^1.2.4
  unbuild: ^3.5.0
  vite: ^5.4.11
  vitest: ^3.1.3
  vue: ^3.5.13
  vue-tsc: ^2.1.10
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
